name: compat-smoke

on:
  push:
    branches: [ fix/python-3.13-shim ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
      - name: CLI smoke test
        run: |
          pwncat-cs --help
      - name: Run tests (if any)
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest -q || true
          fi
